version: "2"

services:
  web:
    build:
      context: web/.
      args:
        - OJS_URL_DOWNLOAD=true
        #- OJS_VCS_CLEANUP=false
        #- OJS_URL_VERSION=2.4.7-1
        #- OJS_PATH=ojs
        #- OJS_GIT_URL=https://github.com/pkp/ojs.git
        #- OJS_GIT_TAG=ojs-2_4_7-1
        #-OJS_SVN_URL=http://svnurl
    volumes:
      - ./web/config.TEMPLATE_DOCKER.inc.php:/var/www/html/config.inc.php
      - ./files:/var/www/html/files 
    ports:
      - "8888:80"
